### ISSUE TITLE
Setup Android Repo

### ISSUE THREAD

**Issue by dalderliesten** [jessetilro/pixelperfect#17]
Set up a basic Android application in a separate software repository on GitHub.

**Comment by jessetilro** [comment]
The repository is set up, containing a basic Android application, and the Continuous Integration server is configured: [https://github.com/jessetilro/pixelperfect-client](https://github.com/jessetilro/pixelperfect-client). The only thing left to do with respect to this issue is configuring Gradle plugins for static analysis purposes.

**Comment by dalderliesten** [comment]
The essential work is done, excellent work.  I'll close the issue for now, if you wish to make an issue for Gradle, please do!
